export const FETCH_SURVEYS = "FETCH_SURVEYS";
export const FETCH_SURVEY = "FETCH_SURVEY";
export const FETCH_QUESTION = "FETCH_QUESTION";
export const FETCH_FILIERES = "FETCH_FILIERES";
export const SET_FILIERE_SCORE = "SET_FILIERE_SCORE";
