export const FETCH_SURVEYS = "FETCH_SURVEYS";
export const CREATE_SURVEY = "CREATE_SURVEY";
export const FETCH_SURVEY = "FETCH_SURVEY";
export const FETCH_FILIERES = "FETCH_FILIERES";
export const SET_FILIERE_SCORE = "SET_FILIERE_SCORE";

// Questions
export const CREATE_QUESTION = "CREATE_QUESTION";
export const FETCH_QUESTION = "FETCH_QUESTION";
export const FETCH_QUESTIONS = "FETCH_QUESTIONS";

// Responses
export const CREATE_RESPONSE = "CREATE_RESPONSE";

// Steps
export const CREATE_STEP = "CREATE_STEP";
